// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApp.DbContext;

#nullable disable

namespace RECEPT_kezelo.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20241128072952_Recept")]
    partial class Recept
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeApp.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bódis Bálint"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Csíkos Marcell"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Czesznak Attila"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vida Tamás"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Papdi Zsombor"
                        });
                });

            modelBuilder.Entity("RecipeApp.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Túró",
                            Quantity = "200g",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rudi",
                            Quantity = "5 db",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tészta",
                            Quantity = "500g",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marha hús",
                            Quantity = "2kg",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Galuska",
                            Quantity = "6db",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tojás",
                            Quantity = "8 db",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Csirke hús",
                            Quantity = "400g",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Víz",
                            Quantity = "1.5l",
                            RecipeId = 3
                        });
                });

            modelBuilder.Entity("RecipeApp.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("RecipeApp.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "A jó húsoknak ;)",
                            Title = "Marhapörkölt"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Full eredeti",
                            Title = "Túró rudi"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Description = "Sok tésztával",
                            Title = "Tészta leves"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Description = "Mindenki kecvence",
                            Title = "Aranygaluska"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Description = "Nagyi féle",
                            Title = "Palacsinta"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            Description = "Csakis csirkéből",
                            Title = "Rántott hús"
                        });
                });

            modelBuilder.Entity("RecipeApp.Entities.Ingredient", b =>
                {
                    b.HasOne("RecipeApp.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApp.Entities.Rating", b =>
                {
                    b.HasOne("RecipeApp.Entities.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApp.Entities.Recipe", b =>
                {
                    b.HasOne("RecipeApp.Entities.Author", "Author")
                        .WithMany("Recipes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("RecipeApp.Entities.Author", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeApp.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
